// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzPWCVr5Cvmgnq2grPlQOQykv5C2xU3og',
    appId: '1:1049538572058:web:b4ac406cc06d78074cc6a3',
    messagingSenderId: '1049538572058',
    projectId: 'nobochitro-official',
    authDomain: 'nobochitro-official.firebaseapp.com',
    storageBucket: 'nobochitro-official.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSc41OgV8lGoFIbcky0L93I1di3okpPh8',
    appId: '1:1049538572058:android:7fa42a0811615ba94cc6a3',
    messagingSenderId: '1049538572058',
    projectId: 'nobochitro-official',
    storageBucket: 'nobochitro-official.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4W4wdacGnv-xwgD5GMpXUYoHf3zIhGvU',
    appId: '1:1049538572058:ios:83dd4a53546d16a94cc6a3',
    messagingSenderId: '1049538572058',
    projectId: 'nobochitro-official',
    storageBucket: 'nobochitro-official.firebasestorage.app',
    iosBundleId: 'com.example.nobochitro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4W4wdacGnv-xwgD5GMpXUYoHf3zIhGvU',
    appId: '1:1049538572058:ios:83dd4a53546d16a94cc6a3',
    messagingSenderId: '1049538572058',
    projectId: 'nobochitro-official',
    storageBucket: 'nobochitro-official.firebasestorage.app',
    iosBundleId: 'com.example.nobochitro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzPWCVr5Cvmgnq2grPlQOQykv5C2xU3og',
    appId: '1:1049538572058:web:d50ca0d74f4f34404cc6a3',
    messagingSenderId: '1049538572058',
    projectId: 'nobochitro-official',
    authDomain: 'nobochitro-official.firebaseapp.com',
    storageBucket: 'nobochitro-official.firebasestorage.app',
  );
}
